@echo off
echo 🚀 Initiating Elite Cafeteria System Launch Sequence...

echo 📡 Starting API Backend...
start cmd /k "cd server && npm start"

echo 🎨 Starting React Storefront...
start cmd /k "cd client && npm run dev"

echo ✨ System synchronization in progress. Redirecting to elite.univ.edu...
timeout /t 5
start http://localhost:5173
